#!/bin/sh
set -euf -o pipefail

##
# Do apt-get remove on old kernel images and headers.
#
# Credit: http://marc.waeckerlin.org/computer/blog/remove_all_old_kernel_images_in_ubuntu
#
# This script removes all old kernels while keeping the running kernel.
#
#
# ## Caution
#
# For your comfort and safety, please upgrade your system
# then reboot before you execute this command to make sure
# the latest kernel is installed and running successfully.
#
# If you get an error, make sure you are running the
# current kernel version, i.e. upgrade then reboot.
#
#
# ## Implementation Notes
#
# We prefer `apt remove --purge` over `apt purge` because the former
# continues to work on older systems, as well as on modern systems.
#
# Note: The plus (+) sign behind a package name inverts the meaning.
# So in the commands below, the plus keeps the running kernel version.
# The uname command finds your actual kernel package version and type.
#
# An alternative implementation can be:
#
#     dpkg --list |
#     grep linux-image |
#     awk '{ print $2 }' |
#     sort -V |
#     sed -n '/'`uname -r`'/q;p' |
#     xargs sudo apt-get purge
#
#
# ## Tracking
#
# Command: apt-purge-old-kernels-and-headers
# Version: 3.0.0
# Created: 2012-11-01
# Updated: 2017-03-31
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

apt-get remove --purge 'linux-image-[0-9].*' linux-image-$(uname -r)+
apt-get remove --purge 'linux-headers-[0-9].*' linux-headers-$(uname -r)+
update-grub2
